### PR TITLE
Add newline to end of README

### PR DESCRIPTION
**Pull request by Eczbek**

### CODE REVIEW

**Comment by Eczbek** [comment]
literally unreadable

**Comment by Tsche** [comment]
The readme should also mention what this repository is for. It's going to contain a more comprehensive reference implementation for a blog post I'm going to publish on pydong.org soon. Exact URL tbd.

Please fix that.

**Review by Tsche — CHANGES_REQUESTED** [review]
The readme should also mention what this repository is.

It is going to contain a reference implementation of the techniques discussed in an upcoming blog post on pydong.org.

Please update accordingly.

**Comment by Tsche** [comment]
no

**Pull request closed without merging**
